### ISSUE TITLE
error when serving up this application with ng serve

### ISSUE THREAD

**Issue by walrus95** [AngularFirebase/60-ngrx-entity-demo#1]
I'm getting an error when trying to serve up this project, saying: Cannot read property 'length' of undefined.

Here are my steps: I clone and install the NPM packages no problem:

```
$ git clone git@github.com:AngularFirebase/60-ngrx-entity-demo.git
$ cd 60-ngrx-entity-demo/
$ npm install

> node-sass@4.5.3 install /home/walrus/proj/60-ngrx-entity-demo/node_modules/node-sass
> node scripts/install.js

Cached binary found at /home/walrus/.npm/node-sass/4.5.3/linux-x64-57_binding.node

> uglifyjs-webpack-plugin@0.4.6 postinstall /home/walrus/proj/60-ngrx-entity-demo/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

> node-sass@4.5.3 postinstall /home/walrus/proj/60-ngrx-entity-demo/node_modules/node-sass
> node scripts/build.js

Binary found at /home/walrus/proj/60-ngrx-entity-demo/node_modules/node-sass/vendor/linux-x64-57/binding.node
Testing binary
Binary is fine
added 992 packages in 10.099s
```

However, I get an error serving up the application:

```
$ ng serve
Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at createSourceFile (/home/walrus/proj/60-ngrx-entity-demo/node_modules/typescript/lib/typescript.js:15457:109)
    at parseSourceFileWorker (/home/walrus/proj/60-ngrx-entity-demo/node_modules/typescript/lib/typescript.js:15389:26)
    at Object.parseSourceFile (/home/walrus/proj/60-ngrx-entity-demo/node_modules/typescript/lib/typescript.js:15338:26)
    at Object.createSourceFile (/home/walrus/proj/60-ngrx-entity-demo/node_modules/typescript/lib/typescript.js:15192:29)
    at VirtualFileStats.getSourceFile (/home/walrus/proj/60-ngrx-entity-demo/node_modules/@ngtools/webpack/src/compiler_host.js:66:35)
    at WebpackCompilerHost.getSourceFile (/home/walrus/proj/60-ngrx-entity-demo/node_modules/@ngtools/webpack/src/compiler_host.js:191:38)
    at findSourceFile (/home/walrus/proj/60-ngrx-entity-demo/node_modules/typescript/lib/typescript.js:67909:29)
    at processImportedModules (/home/walrus/proj/60-ngrx-entity-demo/node_modules/typescript/lib/typescript.js:68056:25)
    at findSourceFile (/home/walrus/proj/60-ngrx-entity-demo/node_modules/typescript/lib/typescript.js:67937:17)
    at processSourceFile (/home/walrus/proj/60-ngrx-entity-demo/node_modules/typescript/lib/typescript.js:67840:27)
    at processRootFile (/home/walrus/proj/60-ngrx-entity-demo/node_modules/typescript/lib/typescript.js:67728:13)
    at /home/walrus/proj/60-ngrx-entity-demo/node_modules/typescript/lib/typescript.js:67018:60
    at Object.forEach (/home/walrus/proj/60-ngrx-entity-demo/node_modules/typescript/lib/typescript.js:1449:30)
    at Object.createProgram (/home/walrus/proj/60-ngrx-entity-demo/node_modules/typescript/lib/typescript.js:67018:16)
    at AotPlugin._setupOptions (/home/walrus/proj/60-ngrx-entity-demo/node_modules/@ngtools/webpack/src/plugin.js:144:28)
    at new AotPlugin (/home/walrus/proj/60-ngrx-entity-demo/node_modules/@ngtools/webpack/src/plugin.js:30:14)
```

For your information:

```
$ ng -v
@angular/cli: 1.4.9
```

**Comment by schnouz** [comment]
you need to add a directory environments in your src. (create a fresh angular app with ng new appName and copy the environments folder into this one)

**Comment by codediodeio** [comment]
Closing issue. FYI, the environment files will be included to prevent this issue for future projects.
